export default {
  colors: {
    primaryColor: '#AA7BE0',
    secondColor:'#8632D2',
    thirtyColor: '#9072E8',
    fourthColor: '#957cdd',
    fifthColor: '#F9C8FF',
    sixthColor: '#FFDFEE',
    seventhColor: '#FDDFFF',

    primaryFontColor: '#EEE4FF',
    secondFontColor: '#F2CCFF',
    thirtyFontColor: '#FDDFFF',
    fourthFontColor: '#BAADEA',
    fifthFontColor: '#CE91E3',
    sixthFontColor: '#E2AFF3',
    seventhFontColor:'#7D7897',

    white: '#FAFAFA',
    black:'#030517',
    appMainWhiteColor: '#F9F9F9',
    appMainGreyColor: '#acacac',
    appMainGreyLightVariantColor: '#ccc',
  },

  sizes: {
    xxsmall: '2px',
    xsmall: '4px',
    small: '8px',
    medium: '12px',
    large: '16px',
    xlarge: '20px',
    xxlarge: '24px',
    xxxlarge: '28px',
    xultralarge: '32px',
    xxultralarge: '36px',
    xxxultralarge: '40px',
    xxxxultralarge: '44px',
    huge: '48px'
  },

  spacings: {
    xxxsmall: '2px',
    xxsmall: '4px',
    xsmall: '8px',
    small: '16px',
    medium: '24px',
    large: '32px',
    xlarge: '40px',
    xxlarge: '48px',
    xxxlarge: '56px',
    xultralarge: '64px',
    xxultralarge: '72px',
    xxxultralarge: '80px',
    xxxxultralarge: '88px',
    huge: '96px',
    xhuge: '104px',
    xxhuge: '108px',
    xxxhuge: '116px',
    xxxxhuge: '124x',
  },

  border: {
    smallRadius: '8px',
    mediumRadius:'16px',
    hugeRadius: '24px'
  },

  font: {
    rubikTitleBlack: 'Rubik-Black',
    rubikTitleBold: 'Rubik-Bold',
    rubikTitleExtraBold: 'Rubik-ExtraBold',
    rubikTitleLight: 'Rubik-Light',
    rubikTitleMedium: 'Rubik-Medium',
    rubikTitleRegular: 'Rubik-Regular',
    rubikTitleSemiBold: 'Rubik-Semibold',
    latoSubTitleBlack: 'Lato-Black',
    latoSubTitleBold: 'Lato-Bold',
    latoSubTitleLight: 'Lato-Light',
    latoSubTitleRegular: 'Lato-Regular',
    heeboTitleButtonBlack: 'Heebo-Black',
    heeboTitleButtonBold: 'Heebo-Bold',
    heeboTitleButtonExtraBold: 'Heebo-ExtraBold',
    heeboTitleButtonExtraLight: 'Heebo-ExtraLight',
    heeboTitleButtonLight: 'Heebo-Light',
    heeboTitleButtonMedium: 'Heebo-Medium',
    heeboTitleButtonRegular: 'Heebo-Regular',
    heeboTitleButtonSemiBold: 'Heebo-SemiBold',
    poppinsPriceAndDiscountBlack: 'Poppins-Black',
    poppinsPriceAndDiscountBold: 'Poppins-Bold',
    poppinsPriceAndDiscountExtraBold: 'Poppins-ExtraBold',
    poppinsPriceAndDiscountExtraLight: 'Poppins-ExtraLight',
    poppinsPriceAndDiscountLight: 'Poppins-Light',
    poppinsPriceAndDiscountMedium: 'Poppins-Medium',
    poppinsPriceAndDiscountRegular: 'Poppins-Regular',
    poppinsPriceAndDiscountSemiBold: 'Poppins-SemiBold',
    light: 200,
    normal: 400,
    bold: 600,
  }
}